### ISSUE TITLE
zshaddhistory() should not use a hardcoded "$HOME/.history"

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#10]
zshaddhistory() should use a hardcoded "$HOME/.history", as not everyone stores their history there.

Perhaps using the zsh $HISTFILE variable would be more appropriate.

**Comment by larkery** [comment]
I think that is some code I forgot to remove, which is a leftover from when I stored the histdb file in that directory and wanted to avoid recording history from within that directory because it made it impossible to ever do a git commit.

It's redundant now and I'll kill it off.
