### ISSUE TITLE
Feature request: A way to import pre-zsh-histdb history

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#11]
I'd like to be able to import in to zsh-histdb's sqlite3 database all the shell history that existed before I started using zsh-histdb, so it can be searched along with the new history I generate after I start using zsh-histdb.

This is important to me as I have tens of thousands of commands in my old history that I'd like to be able to search with histdb rather than having to resort to the old "history 0 | grep" method.

I understand that the timing information and the pwd of the old history will not be available, which is alright, as it's not available to the old history command anyway, so I wouldn't be losing anything by using histdb instead, as long as the history can be imported and the order of the commands is preserved.

**Comment by drewis** [comment]
I wrote a simple tool to do this. https://github.com/drewis/go-histdbimport

**Comment by diamond-lizard** [comment]
Thank you, your tool worked great!

**Comment by larkery** [comment]
I will put this in the readme. Thanks @drewis.
