### ISSUE TITLE
Can a four year old installation be upgraded safely?

### ISSUE THREAD

**Issue by vonHabsi** [larkery/zsh-histdb#118]
Can a four year old installation be upgraded safely?

I installed zsh-histdb four years ago and it is still going strong. Thanks for a very useful utility.

Can I upgrade my installations safely without problems.?

Has the database format changed much since then.

**Comment by tru2dagame** [comment]
Why not do a backup and give it a try? And leave comments how well it does.

**Comment by larkery** [comment]
I believe you might have to change how the code is loaded, there will be something in the changelog in the readme about that.

So in theory it should do some migrations and work. _But_ this promise is subject to my cast-iron SLA guarantee, which is that I guarantee absolutely nothing.
