### ISSUE TITLE
Feature request: Ability to delete entries from database

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#13]
I'd like to be able to delete entries from the database.

It's rare, but on occasion I have been known to do something really stupid like type my password on the command line, and then for security reasons need to delete it out of the history.

This is easy to do when history is stored in plain text, but not so easy when it's in a database (without using specialized tools and taking special care not to screw anything up while doing it).

It's be nice if histdb gave me an easy and safe way to do delete entries.

**Comment by larkery** [comment]
Would something like `histdb --delete 'some text'` be adequate for this, where 'some text' would be a pattern?

I think I already put histdb in the commands to ignore list so this wouldn't itself end up in the history, so if you had entered a password by accident you could say `histdb --delete '%correct horse battery staple%'` and this would remove all history lines containing that substring.

Alternatively, I could print the row ID and allow you to specify row IDs to delete I guess?

Any preference?

**Comment by diamond-lizard** [comment]
I like the row ID selection idea, as long as histdb shows the selected row and prompts for confirmation before it deletes.  I think it has a few advantage over the --delete method:

First, there is no chance that the entry the users wants to delete from the history will show up in the history again, even if they're not ignoring histdb commands.

Second, the row ID method is easily composable with a fuzzy finder like [fzf](https://github.com/junegunn/fzf) or [fzy](https://github.com/jhawthorn/fzy) to allow for fast, easy selection of the row in question (though that's probably overkill for the typical case I described of typing in your pw in to your shell, where you usually realize it right away and looking at just the last line or two of history is sufficient to find the culprit).

Third, it's really simple.  All you need is a row number and that's it.  No need to mess around with copying and pasting potentially complex sequences of characters.  So it seems a bit less error-prone too -- especially if histdb echoes back the selected row and asks for confirmation first.

On the other hand, the --delete/correct method is more flexible in that it will allow the to make arbitrary modifications in history, but at least I personally have had no instances when I've wanted to change the history beyond simply deleting an entire line with a password on it.  So for me this added flexibility would not at the present time be a huge win.  It might for other people, though, so you could potentially add both methods.  I'm personally leaning towards the row ID method, though.

**Comment by larkery** [comment]
I have added the other idea, because it turned out a bit easier to implement.

You can say `histdb --forget some-stuff` and it will show the matches and ask if you want to delete them all.

**Comment by diamond-lizard** [comment]
Thank you for that.  It does solve the particular use case that I opened this issue about: accidentally typing in a password.

If that happens, there should really only be one match, so when histdb displays the results of searching for "some-stuff" to forget, there should really only be a single match so the answer to its prompt of "Forget all these results?" should clearly be "yes" (unless, of course, the user made a typo in telling histdb to forget something, when the answer should be "no").

But now in testing histdb, I've run across another, related use case for deleting history where the above behavior causes some issues.  What happened was that I wanted to test how histdb wrapped its output, so I created and tested cd'ing in to a really, really long path.  This messed up histdb's output, so that now it shows the cmd column pushed way to the right.  Fixing that would be easy, if only I could delete the offending history entry.

The problem is the command in that long directory is not unique.  It's just "pwd", and I have a bunch of other "pwd" commands all of the place, and don't necessarily want to delete them all.  I just want to delete that one particular one.  Also, I wouldn't necessarily in this case want to search by command but by path.

So, ideally, using the --forget search method, histdb would let me search either by command or path, and would let me delete a specific entry, not only all or none entries.

But the above is not critical for me.  I think you've solved my most needed use-case, which is when I accidentally type my password in to the shell.  The other use-cases are more nice-to-haves -- especially as now I'm going to look in to how I can reformat histdb output myself, so I can do my own wrapping and the really long paths won't be such an issue once I do that.

Thanks for all your hard work!

**Comment by larkery** [comment]
So you can do this with the other search parameters I think. If you did something like

```
histdb --forget --at=/some/long/path 
```

it would probably do it.

The `--forget` argument works with all the other query arguments you can use, so you could forget a particular session, or all the commands on a certain host or whatever.

If you produce a better wrapping let me know - like I said I think the 'right thing' to make would be a version of `column` which understands wrapping, I would find that useful in other contexts and I'm sure others would too.

As an alternative I was thinking I could make it so that if the output is very wide it automatically pipes it into a pager - do you think that would be useful?

**Comment by diamond-lizard** [comment]
`histdb --forget --at=/some/long/path` worked.  Thanks.  By the way, it doesn't seem to understand that ~ means $HOME.  Not a big deal, since I can just expand it myself, but just something to be aware of.

As for the pager idea, I already do that myself manually, and it doesn't really help, unfortunately, since the wrapping of long lines is still like described in my feature request on wrapping.

I am thinking of writing a wrapping program that does what I want myself.  It'll be a good exercise for me, since I'm trying to sharpen my Python chops a bit at the moment.  It might just have to wait a bit until I finish another project.  But it can definitely wait.. especially now that I've gotten rid of those really long paths in histdb and my histdb output looks reasonable again, thanks to you!

**Comment by henrebotha** [comment]
At present, this doesn't affect Zsh's own history tracking. Would it not be desirable to extend this function to also remove the offending entries from `~/.zsh_history`?

**Comment by diamond-lizard** [comment]
> At present, this doesn't affect Zsh's own history tracking. Would it not be desirable to extend this function to also remove the offending entries from `~/.zsh_history`?

This would be desirable for me.  I usually have to manually edit my zsh history (which is actually stored in a non-default location, as pointed to using zsh's HISTFILE variable), and it would be much more convenient if zsh-histdb did the right thing itself so I'd only need one command to do it all.

That said, this would need to be completely safe and reliable.  I'd hate to have my zsh history clobbered by mistake.

**Comment by larkery** [comment]
I'd prefer not to make histdb commands affect non-histdb things as it's a bit much responsibility. You could probably get away with this:

```
unhistory () {
   LC_ALL=C sed -i '/'$1'/d' $HISTFILE
   histdb --forget "$1"
}
```
