### ISSUE TITLE
Incorrect documentation regarding multiple search terms

### ISSUE THREAD

**Issue by fberlakovich** [larkery/zsh-histdb#139]
The documentation at https://github.com/larkery/zsh-histdb?tab=readme-ov-file#querying-history states that multiple terms can be combined with `%`. However, using `%` did not work for me. Looking at the code, histdb uses the sqlite3 `GLOB` operator, which expects the usual UNIX wildcards instead of the SQL-like `%`. That is, multiple terms should be combined with `*` and not `%`.

**Comment by larkery** [comment]
Correct - I changed the feature but not the docs, my bad.
