### ISSUE TITLE
Integration with zsh-autosuggestions

### ISSUE THREAD

**Issue by psamim** [larkery/zsh-histdb#14]
Hi,
I added the related function and set the env var for integration with zsh-autosuggestions. I works, but not correctly. It searches history but adds a new line after each suggestion as the screenshot below.

![image](https://user-images.githubusercontent.com/1868679/29739005-b0338f2e-8a22-11e7-9896-6503d746d316.png)

**Comment by fisian** [comment]
Hi,
just installed zsh-histdb and ran into the same problem.
I came up with the following fix:

```sh
_zsh_autosuggest_strategy_histdb_top_here() {
    local query="select commands.argv from
history left join commands on history.command_id = commands.rowid
left join places on history.place_id = places.rowid
where places.dir LIKE '$(sql_escape $PWD)%'
and commands.argv LIKE '$(sql_escape $1)%'
group by commands.argv order by count(*) desc limit 1"
    suggestion=$(_histdb_query "$query")
}

ZSH_AUTOSUGGEST_STRATEGY=histdb_top_here
```

Setting the variable `suggestion` to the result of the query which prevents direct output from the `_histdb_query` function. (This is used in the zsh-autosuggestions [strategies](https://github.com/zsh-users/zsh-autosuggestions/tree/master/src/strategies))
This change should possibly also be included in the README.

**Comment by psamim** [comment]
Thanks @fisian
