### ISSUE TITLE
Error: database is locked

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#16]
While troubleshooting histdb today, I did a `"histdb --limit 21255 |& less"` in one tmux pane, and in another I did a `"man column"` and got this error:

```
Error: database is locked      
error in insert into commands (argv) values ('man column');
insert into places   (host, dir) values ('myhost', '/home/me');
insert into history              
  (session, command_id, place_id, exit_status, start_time, duration)
select     
  580,                                                                                                                                                                                                
  commands.rowid,
  places.rowid,
  0,                      
  1504294750,                                                                  
  1504294750 - 1504294750
from                                
  commands, places                                                                   
where
  commands.argv = 'man column' and
  places.host = 'myhost' and                                                 
  places.dir = '/home/me'
;                 
```

I'm guessing I got this error because histdb was running.  But, since histdb was not actually writing to the database, I'm not sure why it should lock it -- especially if that will keep other shells from writing their history to the database.

**Comment by larkery** [comment]
This is just how `sqlite3` works. I'm not sure there is a way around it; I think it _may_ be possible to open for read without locking if you use sqlite programatically, but I don't think the `sqlite3` command line offers any options about this.

**Comment by diamond-lizard** [comment]
I've thought of this workaround:

histdb could make the sqlite3 connection and get all the data that the user asked for and put it in to a zsh variable.  Then it could close the seqlite3 connection and release the lock.  Finally, it can send the contents of the variable to the user via stdout.

When done this way, histdb would have the database locked only for the time it takes to read the data from sqlite3, and even if the user pipes histdb through less like I did and keep that process alive and unclosed for years, it would not affect other processes trying to access the sqlite3 database.

Only during the brief time histdb read from the database would the lock prevent other processes from writing to it.  Of course, even in that brief time, there could conceivably be other accesses, but at least the chance of that happening will be minimized by this solution, I think.

**Comment by larkery** [comment]
Yeah, I was thinking I will probably test if stdout is a pipe and buffer it up if it is.

**Comment by larkery** [comment]
So I've pushed a change which may or may not be good. It does two things:

1. if stdout is a pipe, do the thing you said (albeit using perl as this was easier to write down)
2. also if stdout is a pipe, print all the matches rather than 1 screenful

See if this is useful to you

**Comment by diamond-lizard** [comment]
It seems to work great.  I tried `histdb --limit 100000 | less` and while that was open, in another tmux pane to cd around, and no lock error occured, and the entries from this new shell session were saved to histdb successfully.  Thanks!
