### ISSUE TITLE
Duration and exit status is not recorded correctly

### ISSUE THREAD

**Issue by olejorgenb** [larkery/zsh-histdb#18]
Duration/timing and exit status is offset one command in the past due to the ordering of `precmd`, `preexec` and `zshhistoryadd`

To reproduce:

    echo this command takes 0 seconds
    sleep 10
    echo this command will stored with 10s duration
    false
    true
    sqlite3 --column --header  ~/.histdb/zsh-history.db \
         "select exit_status, start_time, duration, argv from history, commands where commands.rowid = history.command_id order by start_time desc LIMIT 6;"

From README:

    autoload -Uz add-zsh-hook
    add-zsh-hook preexec _start_timer
    add-zsh-hook precmd  _stop_timer

The history is recorded using `zshhistoryadd` which is called just [before](https://github.com/zsh-users/zsh/blob/97d4bdbc7e86e6e8da0d4a059b118ffab289d3a9/Src/init.c#L166) `preexec`

Timeline tracing `command-1` and `command-2`:

     command-1 is typed and executed by user
     zshhistoryadd
       Neither _STARTED or _FINISHED set. command-1 saved with 0 duration
     preexec
       _STARTED set
     command-1 finishes
     precmd
      _FINISHED set
     command-2 is typed and executed by user
     zshhistoryadd
       command-2 is saved with the duration of command-1
       
Doc reference:

    precmd Executed before each prompt.  Note that precommand functions are not re-executed simply
          because the command line is redrawn, as happens, for example, when a notification about
          an exiting job is displayed.

    preexec
          Executed  just  after a command has been read and is about to be executed.  If the his‐
          tory mechanism is active (regardless of whether the line was discarded from the history
          buffer),  the  string that the user typed is passed as the first argument, otherwise it
          is an empty string.  The actual command  that  will  be  executed  (including  expanded
          aliases)  is  passed  in  two  different  forms:  the second argument is a single-line,
          size-limited version of the command (with things  like  function  bodies  elided);  the
          third argument contains the full text that is being executed.
 

Disclaimer: I do have `inc_append_history_time` set and haven't tested without it, but looking at the code and doc I don't see how it would affect things.

**Comment by olejorgenb** [comment]
In https://github.com/spacelis/zsh-historykeeper the histroy is written in the `precmd` hook to ensure correct timing.

**Comment by larkery** [comment]
Hah, OK. Sloppy work by me, I'll tidy it up.

**Comment by larkery** [comment]
I think I've fixed this, but it requires different config

**Comment by codequokka** [comment]
I have same issue on current version.
Do you have any idea to fix this?

```SQL
SELECT
  *
FROM
  history
WHERE
  exit_status IS NULL OR
  duration IS NULL
LIMIT
  5
```

|session|command_id|place_id|exit_status|start_time|duration|
|-------|-------------|---------|----------|---------|---------|
1|11|2|NULL|1557661462|NULL
9|61|2|NULL|1557662265|NULL
12|89|12|NULL|1557665488|NULL
12|89|12|NULL|1557666301|NULL
10|104|12|NULL|1557666919|NULL
