### ISSUE TITLE
buffer:3: file exists: /tmp/tmp.KzWP3NvU39

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#22]
After upgrading to the newest version of histdb, whenever I pipe `histdb` or `histdb --limit X` (where X is any integer) through another command like `more` or `less` I get a `buffer:3: file exists` error.

For example:

```
> histdb --limit 10 | more         
buffer:3: file exists: /tmp/tmp.TEUwD26gtS
(showing 10 of 27797 results)
```

The actual tmp file name varies from run to run.  One run it's `/tmp/tmp.TEUwD26gtS` another it's `/tmp/tmp.NTzAMhH1TY`

Piping just `histdb` without any argument through `more` or `less` gives the same error.

Running `histdb` (with or without the `--limit` argument) **without** piping it through another program works normally.

Here is the output of `histdb --limit 10 -d | less`

```
select strftime(case when datetime(max_start, 'unixepoch') > datetime('now', 'start of day') then '%H:%M' else '%d/%m' end, max_start, 'unixepoch', 'localtime') as time, session as ses, dir, argv as cmd from (select session, replace(places.dir, '/home/me', '~') as dir, replace(commands.argv, '
', '
^_^_^_') as argv, max(start_time) as max_start
from
  history
  left join commands on history.command_id = commands.rowid
  left join places on history.place_id = places.rowid
where not (commands.argv like 'histdb%') and places.host='myhost'
group by history.command_id, history.place_id
order by max_start desc
limit 10) order by max_start asc
```

**Comment by larkery** [comment]
Argh, this is a ZSH setting again which I don't have and you do (noclobber).

I'm using mktemp to make a temp file and then appending to it, which breaks with noclobber.
I have just pushed a commit which should work by changing the relevant > to >! instead.

**Comment by diamond-lizard** [comment]
It works great now.  Thanks!
