### ISSUE TITLE
Why place_id and duration columns in history table are NULL?

### ISSUE THREAD

**Issue by codequokka** [larkery/zsh-histdb#45]
When I queried for history table, I fonud place_id, duration columuns are sometimes NULL.

```SQL
SELECT
  *
FROM
  history
WHERE
  exit_status IS NULL OR
  duration IS NULL
LIMIT
  5
```

|session|command_id|place_id|exit_status|start_time|duration|
|-------|-------------|---------|----------|---------|---------|
1|11|2|NULL|1557661462|NULL
9|61|2|NULL|1557662265|NULL
12|89|12|NULL|1557665488|NULL
12|89|12|NULL|1557666301|NULL
10|104|12|NULL|1557666919|NULL

Do you have any idea why these columns are NULL?
This seems to be same issue #18.

**Comment by m42e** [comment]
Did you register the hook for updating the time?

```
add-zsh-hook precmd histdb-update-outcome
```

**Comment by codequokka** [comment]
@m42e 

Yes I did.
My .zshrc has following settings for zsh-histdb.

```
HISTDB_TABULATE_CMD=(sed -e $'s/\x1f/\t/g')
autoload -Uz add-zsh-hook
add-zsh-hook precmd histdb-update-outcome
```

**Comment by m42e** [comment]
Which OS are you using?

**Comment by codequokka** [comment]
I'm using macOS 10.14.

**Comment by m42e** [comment]
Do you See this issue for all Commands or just some or sometimes? The hook writing these values is actually the precedent hook, if the terminal has been exited and no comeliness has been drawn or the job was a background job or things like that may cause such entries.

**Comment by codequokka** [comment]
It happens with a probability of about 8%(299/3427).

I checked which command it caused following SQL.
```SQL
SELECT
  commands.argv,
  count(*)
FROM
  history
    left join commands on history.command_id = commands.rowid
WHERE
  history.duration IS NULL OR
  history.exit_status IS NULL
GROUP by
  commands.argv
ORDER by
  count(*) DESC
LIMIT
  10
```

It seems almost all of command stays on foreground for a while.
Do you have any idea on this?

|argv|count(*)|
|----|---------|
docker-compose up | 57
docker-compose up logstash | 40
docker-compose up elasticsearch | 34
tmux | 16
vagrant ssh | 16
sqlite3 ~/.zsh_history.db | 13
logstash -f ~/Downloads/debug.conf | 12
ghq look https://github.com/codequokka/shell-history-analyzer | 10
docker-compose up kibana | 8
exit | 8

**Comment by m42e** [comment]
Well, I had a look, and it seems the update outcome does not respect the id of the current session. So it looks for the highest id available, rather than the highest id of the current session.

I did a change which is changing this behaviour and also does not depend on a variable to update the status but rather uses the database to look up if an exit status has been reported.

See: https://github.com/larkery/zsh-histdb/pull/46
NB: I have not tested this well, in my fork I also introduced ids instead of using the row_id but I don't think it interferes with that.

**Comment by codequokka** [comment]
Thank you for creating new branch.
I tried it but some error happnes

```
Error: near line 1: no such column: id
error in
```

Is there anything wrong?

**Comment by m42e** [comment]
ok, that was definitely my fault, as I had this based on another change/PR I made.
I updated the #46.

**Comment by codequokka** [comment]
I tried it out updated branch(1b44c13), but same error happed:(

```
Error: near line 1: no such column: id
error in
```

**Comment by larkery** [comment]
Try the current master branch, which should include Matthias' fixes.

**Comment by alexghergh** [comment]
This seems to still be happening?

I am having issues while trying to retrieve the status codes. Most of the commands in the SQLite database have no status codes (as well as no timings).

I only have
```
source $HOME/.oh-my-zsh/custom/plugins/zsh-histdb/sqlite-history.zsh
autoload -Uz add-zsh-hook
```

in my .zshrc (version 5.8).

It only seems to be happening with some commands that affect the shell or the database in some way (sqlite3 when accessing the database, reboot, source when trying to reload the .zshrc file). Other commands seem to work fine.
