### ISSUE TITLE
Feature request: Search backward/forward

### ISSUE THREAD

**Issue by fuero** [larkery/zsh-histdb#56]
I'm using these ZSH widgets for history search:

> bindkey "^[[5~" history-beginning-search-backward       # page up
> bindkey "^[[6~" history-beginning-search-forward        # page down

I'd like to use zsh-histdb the same way.

**Comment by larkery** [comment]
I don't do feature requests (zsh-histdb exists primarily to help me with my needs) but will look at a pull request implementing the relevant widgets.
