### ISSUE TITLE
wildcards search with % didn't work.

### ISSUE THREAD

**Issue by tru2dagame** [larkery/zsh-histdb#60]
Hi 

> For wildcards within a history line, you can use the % character, which is like the shell glob *, so histdb this%that will match any history line containing this followed by that with zero or more characters in-between.

I tried both `this%that` and `this*that` with -d to debug. 

Turns out that `this%that` didn't work. 
And this one `histdb this\*that` works for me.

![image](https://user-images.githubusercontent.com/1673006/68085148-81e04500-fe78-11e9-9fe4-03eecba8ecdf.png)

**Comment by pyrho** [comment]
Same here.
Looking at the output of the `-d` invocation, it looks like the query now uses the `GLOB` [1] oeprator which uses `*` for 0..n characters and `?` for a single character.

I guess that it used to rely on the `LIKE` operator when the README was written.

1: https://www.tutorialspoint.com/sqlite/sqlite_glob_clause.htm

**Comment by larkery** [comment]
This is correct - the README is maintained with the same quality guarantee as the rest of the software I'm afraid.
