### ISSUE TITLE
histdb-sync fails to append to .gitattributes if NO_CLOBBER is set

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#7]
When the "NO_CLOBBER" zsh option is set, the first time histdb-sync runs, it will fail to append to the .gitattributes file, because that file does not yet exist and the "NO_CLOBBER" zsh option prevents appending to a non-existent file.

The solution would probably be to test for the existence of .gitattributes first, then use > if it doesn't exist, and >> if it does.

**Comment by ChiefGhostZero0x1** [comment]
This is a good project as I am overwhelmed with this.
