### ISSUE TITLE
Recover history to zsh_history

### ISSUE THREAD

**Issue by edsonlima** [larkery/zsh-histdb#72]
Hi, for some strange reason, my zsh_history disappears randomly. There is no disk errors, no corruptions on it, it simply goes away. It is important to say, this is absolutly not related with zsh-histdb. This problem occours even after a fresh install of Manjaro, and seems related with the size of zsh_history with oh_my_zsh. 

But... the question here is:

Thanks to zsh-histdb, I have a fresh copy of it, but how to recover the history back to zsh_history file?

Thanks in advance.

**Comment by larkery** [comment]
I don't know the format for the zsh_history file. If you can find this out then it is probably quite easy to write a query to reconstruct it. Have a look at uses of _histdb_query to see how.
