### ISSUE TITLE
Exclude commands from db?

### ISSUE THREAD

**Issue by tmpm697** [larkery/zsh-histdb#78]
how can I exclude some commands from saving into sqlite3 db?

**Comment by phiresky** [comment]
you can append to or redeclare _BORING_COMMANDS:

https://github.com/larkery/zsh-histdb/blob/deb8cb695449be90074667903f3a70eafad7f1d4/sqlite-history.zsh#L108

**Comment by larkery** [comment]
What he said

**Comment by tmpm697** [comment]
@phiresky : Is there a way to exlucde failed command form saving into db?

**Comment by phiresky** [comment]
not that i know of, but it would probably be more useful to filter the histdb output by exit status since it is saved in the db

**Comment by larkery** [comment]
phiresky's suggestion is the right one. I'll add it in as I think I'd find that useful.

To prevent failed commands being saved ever is difficult because history logging is triggered when the command is executed, not when it completes. You would need to change how the whole thing works.

You could do like what `_histdb_update_outcome` does with something like this (untested) stuff

```
_histdb_forget_failures () {
local retval=$?
[[ -z "${HISTDB_SESSION}" ]] && return
_histdb_init
_histdb_query_batch <<EOF &|
delete from hsitory where id=(select max(id) from history) and session = ${HISTDB_SESSION} and exit_status is not null and exit_status <> 0
EOF
}

add-zsh-hook precmd _histdb_forget_failures
```

**Comment by tmpm697** [comment]
@larkery : Yes it worked, but how can we delete previous failed commands?

**Comment by larkery** [comment]
run some sql I guess

```
_histdb_query 'delete from history where exit_status is not null and exit_status <> 0'
```

I suggest reading the code a bit to see how it works. Nothing in here is very complicated, which is why there isn't all that much user interface.

**Comment by tmpm697** [comment]
Thanks, do you mind to give it a shot to merge `_histdb_forget_failures` into `masster`?

**Comment by larkery** [comment]
I don't intend to as I don't want it as a feature, but if you want that effect you can paste the code into your zshrc, or modify the source in a clone of the repo or what have you.
