### ISSUE TITLE
fatal: pathspec 'zsh-history.db' did not match any files

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#8]
If histdb-sync is the first command that's run after sourcing sqlite-history.zsh then histdb-sync will error out with "fatal: pathspec 'zsh-history.db' did not match any files" because the $HISTDB_FILE file will only be created after the first command has been run.

histdb-sync should check to make sure that $HISTDB_FILE exists instead of assuming it does, and act accordingly (probably by creating that file if it doesn't already exist).

**Comment by ChiefGhostZero0x1** [comment]
Can you make something where a user can plug-in their repos or just check their whole account all repos .... just realized it's all of GitHub that needs tine checked...  I know I have a huge problem with hashicorp....specially on the outside or cut-off/hidden from view part that isn't visible to the outside but it's very much visible and of great value from my perspective.![image](https://user-images.githubusercontent.com/89703573/147964511-1852e993-2fff-4514-98cc-5396340f9bba.png)![image](https://user-images.githubusercontent.com/89703573/147964535-90cae714-aa89-49d5-9d2d-df8ebbe33b7d.png)

I have no idea if it will populate data when I hit the save button and make me look silly again but here we go again!!!

**Comment by ChiefGhostZero0x1** [comment]
The pics are from the dark side of the moon for a good name candidate to refer to the lost code
