### ISSUE TITLE
stat: illegal option -- c on macOS

### ISSUE THREAD

**Issue by sumanthratna** [larkery/zsh-histdb#80]
I've loaded the library via [antibody](https://getantibody.github.io). When I run any command, the output is followed by:
```
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c                                                                                                       
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```
https://stackoverflow.com/a/10666606/7127932 proposes some solutions. We could:
- require macOS users to install stat via homebrew. in this library, detect if the user is on macOS or not, and set the stat executable to either `gstat` or `stat`
- don't require macOS users to install stat via homebrew. in this library, detect if the user is on macOS or not, and call either `stat -f` or `stat -c`
- use perl 5, which I believe is installed by default on macOS

https://github.com/larkery/zsh-histdb/blob/8a7ae6f43785ff2be597e65b24b471a3ce94a9a4/sqlite-history.zsh#L48-L68

**Comment by larkery** [comment]
Since this is zsh I think we can use zstat instead. I have pushed a commit which does this.

**Comment by sumanthratna** [comment]
I just updated; the issue still occurs.

**Comment by sumanthratna** [comment]
@larkery 
https://github.com/larkery/zsh-histdb/blob/3c95d377fcdab1852069e81b2e61f2334cbbdd06/sqlite-history.zsh#L60-L68

It looks like 3c95d377fcdab1852069e81b2e61f2334cbbdd06 didn't change all instances of `stat`.

**Comment by larkery** [comment]
Test in production for maximum professionalism. Should be fixed now.
