### ISSUE TITLE
histdb-sync fails with:  "fatal: No remote repository specified"

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#9]
When I run histdb-sync, it fails with:

> fatal: No remote repository specified.  Please, specify either a URL or a
> remote name from which new revisions should be fetched.

I think this error comes from the "git pull --no-edit" command in histdb-sync, but I'm not sure why it's happening.  The full log of my histdb-sync run is:

> Initialized empty Git repository in /home/me/.zsh-private/histdb/.git/
> [master (root-commit) 2d84036] history
>  2 files changed, 1 insertion(+)
>  create mode 100644 .gitattributes
>  create mode 100644 histdb.sqlite3
> fatal: No remote repository specified.  Please, specify either a URL or a
> remote name from which new revisions should be fetched.

**Comment by larkery** [comment]
You need to add a remote for this to work, as the command's purpose is to push/pull history to another machine. Something like

```
git remote add origin some.host.com:/some/repo.git
```

Would do the trick, perhaps also with a `git push -u origin master` or similar.
